name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/ga-ec2
          chmod 600 ~/.ssh/ga-ec2
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/ga-ec2

      - name: Deploy code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/mern-deploy
            git pull origin main
            cd backend && pm2 restart all || pm2 start npm -- start
            cd ../frontend && npm install && npm run build
            sudo systemctl restart nginx
          EOF
